version: '3'

services:
  # db:
  #   container_name: mysql-ku-bart
  #   image: mysql:8
  #   env_file: ./.env
  #   ports:
  #     - 3307:3307
  ku-bart:
    container_name: ku-bart
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      shm_size: 80gb
    volumes:
      - /work/tomishima2904/explore_conceptnet:/work/tomishima2904/explore_conceptnet
    ports:
      - '4416:4416'
    stdin_open: true
    tty: true
    # depends_on:
    #   - db
